-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = nil

-- Highlight groups
local hi = vim.api.nvim_set_hl

local light_red = "#ffaabb"

hi(0, "@keyword.return", { ctermfg = 217, fg = light_red})
hi(0, "@lsp.mod.deprecated", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "@lsp.type.variable", { ctermfg = 210, fg = "#ff7799" })
hi(0, "@markup.heading.1", { link = "markdownH1" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#100020", fg = "#100020", nocombine = true, sp = "#ff7799", underdouble = true })
hi(0, "@markup.heading.2", { link = "markdownH2" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#100020", fg = "#100020", nocombine = true, sp = "#ff7799", underline = true })
hi(0, "@markup.heading.3", { link = "markdownH3" })
hi(0, "@markup.heading.4", { link = "markdownH4" })
hi(0, "@markup.heading.5", { link = "markdownH5" })
hi(0, "@markup.heading.6", { link = "markdownH6" })
hi(0, "@string.special.vimdoc", { link = "SpecialChar" })
hi(0, "@symbol", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@variable", { ctermfg = 210, fg = "#ff7799" })
hi(0, "@variable.parameter.vimdoc", { ctermfg = 228, fg = "#ffff99" })
hi(0, "Added", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { ctermfg = 228, fg = "#ffff99" })
hi(0, "Changed", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "Character", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "ColorColumn", { bg = "#202040", ctermbg = 4 })
hi(0, "Comment", { ctermfg = 103, fg = "#8691a7" })
hi(0, "Conceal", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "Conditional", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "Constant", { ctermfg = 228, fg = "#ffff99" })
hi(0, "CurSearch", { bg = "#ffff99", ctermbg = 228, ctermfg = 4, fg = "#202040" })
hi(0, "Cursor", { bg = "#ff7799", ctermbg = 210, ctermfg = 233, fg = "#100020" })
hi(0, "CursorColumn", { bg = "#202040", ctermbg = 4 })
hi(0, "CursorIM", { bg = "#ff7799", ctermbg = 210, ctermfg = 233, fg = "#100020" })
hi(0, "CursorLine", { bg = "#202040", ctermbg = 4 })
hi(0, "CursorLineFold", { bg = "#202040", ctermbg = 4, ctermfg = 170, fg = "#ca6ecf" })
hi(0, "CursorLineNr", { bg = "#202040", ctermbg = 4, ctermfg = 15, fg = "#ffffff" })
hi(0, "CursorLineSign", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "Debug", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "Define", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "Delimiter", { ctermfg = 38, fg = "#00a5c5" })
hi(0, "DiagnosticError", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "DiagnosticFloatingError", { bg = "#202040", ctermbg = 4, ctermfg = 217, fg = "#ffaabb" })
hi(0, "DiagnosticFloatingHint", { bg = "#202040", ctermbg = 4, ctermfg = 87, fg = "#42f7ff" })
hi(0, "DiagnosticFloatingInfo", { bg = "#202040", ctermbg = 4, ctermfg = 170, fg = "#ca6ecf" })
hi(0, "DiagnosticFloatingOk", { bg = "#202040", ctermbg = 4, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "DiagnosticFloatingWarn", { bg = "#202040", ctermbg = 4, ctermfg = 219, fg = "#ffaaff" })
hi(0, "DiagnosticHint", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "DiagnosticInfo", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "DiagnosticOk", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "DiagnosticSignError", { link = "DiagnosticFloatingError" })
hi(0, "DiagnosticSignHint", { link = "DiagnosticFloatingHint" })
hi(0, "DiagnosticSignInfo", { link = "DiagnosticFloatingInfo" })
hi(0, "DiagnosticSignOk", { link = "DiagnosticFloatingOk" })
hi(0, "DiagnosticSignWarn", { link = "DiagnosticFloatingWarn" })
hi(0, "DiagnosticUnderlineError", { sp = "#ffaabb", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#42f7ff", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#ca6ecf", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#aaf0d1", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ffaaff", underline = true })
hi(0, "DiagnosticWarn", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "DiffAdd", { bg = "#202040", ctermbg = 4, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "DiffChange", { bg = "#202040", ctermbg = 4, ctermfg = 219, fg = "#ffaaff" })
hi(0, "DiffDelete", { bg = "#202040", ctermbg = 4, ctermfg = 217, fg = "#ffaabb" })
hi(0, "DiffText", { bg = "#202040", ctermbg = 4, ctermfg = 87, fg = "#42f7ff" })
hi(0, "Directory", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "EndOfBuffer", { blend = 0, ctermfg = 103, fg = "#8691a7" })
hi(0, "Error", { bg = "#ffaabb", ctermbg = 217, ctermfg = 233, fg = "#100020" })
hi(0, "ErrorMsg", { bg = "#100020", ctermbg = 233, ctermfg = 217, fg = "#ffaabb" })
hi(0, "Exception", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "Float", { ctermfg = 228, fg = "#ffff99" })
hi(0, "FoldColumn", { bg = "#202040", ctermbg = 4, ctermfg = 170, fg = "#ca6ecf" })
hi(0, "Folded", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "Function", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "Identifier", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "Ignore", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "IncSearch", { bg = "#ffff99", ctermbg = 228, ctermfg = 4, fg = "#202040" })
hi(0, "Include", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "Label", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "LineNr", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "LineNrAbove", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "LineNrBelow", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#202040", ctermbg = 235 })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "Macro", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "MatchParen", { bg = "#202040", ctermbg = 235 })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "NormalFloat" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#202040", bold = true, ctermbg = 4, ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverChangeBuf", { link = "MiniDiffOverChange" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { bg = "#202040", ctermbg = 4, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MiniDiffSignChange", { bg = "#202040", ctermbg = 4, ctermfg = 219, fg = "#ffaaff" })
hi(0, "MiniDiffSignDelete", { bg = "#202040", ctermbg = 4, ctermfg = 217, fg = "#ffaabb" })
hi(0, "MiniFilesBorder", { link = "NormalFloat" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { bg = "#202040", ctermbg = 235 })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { ctermfg = 210, fg = "#ff7799" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { bg = "#202040", ctermbg = 4, ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniFilesTitleFocused", { bg = "#202040", bold = true, ctermbg = 4, ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniHipatternsFixme", { bg = "#ffaabb", bold = true, ctermbg = 217, ctermfg = 233, fg = "#100020" })
hi(0, "MiniHipatternsHack", { bg = "#ffaaff", bold = true, ctermbg = 219, ctermfg = 233, fg = "#100020" })
hi(0, "MiniHipatternsNote", { bg = "#42f7ff", bold = true, ctermbg = 87, ctermfg = 233, fg = "#100020" })
hi(0, "MiniHipatternsTodo", { bg = "#ca6ecf", bold = true, ctermbg = 170, ctermfg = 233, fg = "#100020" })
hi(0, "MiniIconsAzure", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniIconsBlue", { ctermfg = 38, fg = "#00a5c5" })
hi(0, "MiniIconsCyan", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "MiniIconsGreen", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MiniIconsGrey", { ctermfg = 105, fg = "#9977ff" })
hi(0, "MiniIconsOrange", { ctermfg = 228, fg = "#ffff99" })
hi(0, "MiniIconsPurple", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "MiniIconsRed", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "MiniIconsYellow", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "MiniIndentscopeSymbol", { ctermfg = 38, fg = "#00a5c5" })
hi(0, "MiniIndentscopeSymbolOff", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bg = "#202040", bold = true, ctermbg = 4, ctermfg = 105, fg = "#9977ff", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#100020", ctermbg = 233, ctermfg = 159, fg = "#aaffff", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#202040", ctermbg = 4, ctermfg = 210, fg = "#ff7799" })
hi(0, "MiniMapSymbolCount", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "MiniMapSymbolLine", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniMapSymbolView", { ctermfg = 38, fg = "#00a5c5" })
hi(0, "MiniNotifyBorder", { link = "NormalFloat" })
hi(0, "MiniNotifyLspProgress", { link = "MiniNotifyNormal" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "NormalFloat" })
hi(0, "MiniPickBorderBusy", { bg = "#202040", ctermbg = 4, ctermfg = 219, fg = "#ffaaff" })
hi(0, "MiniPickBorderText", { bg = "#202040", bold = true, ctermbg = 4, ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { ctermfg = 210, fg = "#ff7799" })
hi(0, "MiniPickMatchCurrent", { bg = "#202040", ctermbg = 235 })
hi(0, "MiniPickMatchMarked", { bg = "#8691a7", ctermbg = 103 })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { bg = "#202040", ctermbg = 235 })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "MiniPickMatchRanges" })
hi(0, "MiniPickPromptCaret", { bg = "#202040", ctermbg = 4, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MiniPickPromptPrefix", { bg = "#202040", ctermbg = 4, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MiniSnippetsCurrent", { sp = "#ffaaff", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#ffaabb", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#aaf0d1", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#42f7ff", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#ca6ecf", underdouble = true })
hi(0, "MiniStarterFooter", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniStarterHeader", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { ctermfg = 210, fg = "#ff7799" })
hi(0, "MiniStarterItemBullet", { ctermfg = 38, fg = "#00a5c5" })
hi(0, "MiniStarterItemPrefix", { bold = true, ctermfg = 217, fg = "#ffaabb" })
hi(0, "MiniStarterQuery", { bold = true, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MiniStarterSection", { ctermfg = 38, fg = "#00a5c5" })
hi(0, "MiniStatuslineDevinfo", { bg = "#202040", ctermbg = 235, ctermfg = 15, fg = "#ffffff" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#ffaabb", bold = true, ctermbg = 217, ctermfg = 233, fg = "#100020" })
hi(0, "MiniStatuslineModeInsert", { bg = "#42f7ff", bold = true, ctermbg = 87, ctermfg = 233, fg = "#100020" })
hi(0, "MiniStatuslineModeNormal", { bg = "#ff7799", bold = true, ctermbg = 210, ctermfg = 233, fg = "#100020" })
hi(0, "MiniStatuslineModeOther", { bg = "#8691a7", bold = true, ctermbg = 103, ctermfg = 233, fg = "#100020" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ffaaff", bold = true, ctermbg = 219, ctermfg = 233, fg = "#100020" })
hi(0, "MiniStatuslineModeVisual", { bg = "#aaf0d1", bold = true, ctermbg = 158, ctermfg = 233, fg = "#100020" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#202040", bold = true, ctermbg = 235, ctermfg = 210, fg = "#ff7799" })
hi(0, "MiniTablineFill", {})
hi(0, "MiniTablineHidden", { bg = "#202040", ctermbg = 4, ctermfg = 15, fg = "#ffffff" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#ff7799", bold = true, ctermbg = 210, ctermfg = 235, fg = "#202040" })
hi(0, "MiniTablineModifiedHidden", { bg = "#ffffff", ctermbg = 15, ctermfg = 4, fg = "#202040" })
hi(0, "MiniTablineModifiedVisible", { bg = "#ffffff", bold = true, ctermbg = 15, ctermfg = 235, fg = "#202040" })
hi(0, "MiniTablineTabpagesection", { bg = "#aaaaff", bold = true, ctermbg = 147, ctermfg = 4, fg = "#202040" })
hi(0, "MiniTablineTrunc", { bg = "#202040", bold = true, ctermbg = 4, ctermfg = 210, fg = "#ff7799" })
hi(0, "MiniTablineVisible", { bg = "#202040", bold = true, ctermbg = 4, ctermfg = 210, fg = "#ff7799" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, ctermfg = 217, fg = "#ffaabb" })
hi(0, "MiniTestPass", { bold = true, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MiniTrailspace", { link = "Error" })
hi(0, "ModeMsg", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MoreMsg", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "MsgArea", { blend = 0, ctermfg = 210, fg = "#ff7799" })
hi(0, "MsgSeparator", { blend = 0, ctermfg = 15, fg = "#ffffff" })
hi(0, "NonText", { ctermfg = 103, fg = "#8691a7" })
hi(0, "Normal", { blend = 0, ctermfg = 210, fg = "#ff7799" })
hi(0, "NormalFloat", { bg = "#202040", ctermbg = 4, ctermfg = 210, fg = "#ff7799" })
hi(0, "NormalNC", { blend = 0, ctermfg = 210, fg = "#ff7799" })
hi(0, "Number", { ctermfg = 228, fg = "#ffff99" })
hi(0, "Operator", { ctermfg = 210, fg = "#ff7799" })
hi(0, "Pmenu", { bg = "#000000", blend = 40, ctermbg = 4, ctermfg = 210, fg = "#ff7799" })
hi(0, "PmenuExtra", { bg = "#9977ff", ctermbg = 4, ctermfg = 210, fg = "#ff7799" })
hi(0, "PmenuExtraSel", { bg = "#9977ff", ctermbg = 4, ctermfg = 210, fg = "#ff7799", reverse = true })
hi(0, "PmenuKind", { bg = "#9977ff", ctermbg = 4, ctermfg = 210, fg = "#ff7799" })
hi(0, "PmenuKindSel", { bg = "#000000", ctermbg = 4, ctermfg = 210, fg = "#ff7799", reverse = true })
hi(0, "PmenuMatch", { bg = "#ffffff", blend = 40, bold = true, ctermbg = 4, ctermfg = 210, fg = "#000000" })
hi(0, "PmenuMatchSel", { bg = "#ffffff", blend = 20, bold = true, ctermbg = 4, ctermfg = 210, fg = "#000000", reverse = true })
hi(0, "PmenuSbar", { bg = "#202040", ctermbg = 235 })
hi(0, "PmenuSel", { bg = "#ffffff", ctermbg = 4, ctermfg = 210, fg = "#000000" })
hi(0, "PmenuThumb", { bg = "#9977ff", ctermbg = 105 })
hi(0, "PreCondit", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "PreProc", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "Question", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "QuickFixLine", { bg = "#202040", ctermbg = 4 })
hi(0, "Removed", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "Repeat", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "Search", { bg = "#aaaaff", ctermbg = 147, ctermfg = 4, fg = "#202040" })
hi(0, "SignColumn", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "Special", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "SpecialChar", { ctermfg = 38, fg = "#00a5c5" })
hi(0, "SpecialComment", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "SpecialKey", { ctermfg = 103, fg = "#8691a7" })
hi(0, "SpellBad", { sp = "#ffaabb", undercurl = true })
hi(0, "SpellCap", { sp = "#42f7ff", undercurl = true })
hi(0, "SpellLocal", { sp = "#ca6ecf", undercurl = true })
hi(0, "SpellRare", { sp = "#ffaaff", undercurl = true })
hi(0, "Statement", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "StatusLine", { bg = "#202040", ctermbg = 235, ctermfg = 15, fg = "#ffffff" })
hi(0, "StatusLineNC", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "StorageClass", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "String", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "Structure", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "Substitute", { bg = "#aaaaff", ctermbg = 147, ctermfg = 4, fg = "#202040" })
hi(0, "TabLine", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "TabLineFill", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "TabLineSel", { bg = "#202040", ctermbg = 4, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "Tag", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "Todo", { bg = "#202040", ctermbg = 4, ctermfg = 147, fg = "#aaaaff" })
hi(0, "TooLong", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "Type", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "Typedef", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "VertSplit", { blend = 0, ctermfg = 235, fg = "#202040" })
hi(0, "Visual", { bg = "#202040", ctermbg = 235 })
hi(0, "VisualNOS", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "WarningMsg", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "Whitespace", { ctermfg = 103, fg = "#8691a7" })
hi(0, "WildMenu", { bg = "#aaaaff", ctermbg = 147, ctermfg = 217, fg = "#ffaabb" })
hi(0, "WinBar", { bg = "#202040", ctermbg = 235, ctermfg = 15, fg = "#ffffff" })
hi(0, "WinBarNC", { bg = "#202040", ctermbg = 4, ctermfg = 103, fg = "#8691a7" })
hi(0, "WinSeparator", { blend = 0, ctermfg = 235, fg = "#202040" })
hi(0, "diffAdded", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "diffChanged", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "diffFile", { ctermfg = 228, fg = "#ffff99" })
hi(0, "diffLine", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "diffRemoved", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "gitcommitBranch", { bold = true, ctermfg = 228, fg = "#ffff99" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, ctermfg = 217, fg = "#ffaabb" })
hi(0, "gitcommitDiscardedType", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "gitcommitHeader", { ctermfg = 219, fg = "#ffaaff" })
hi(0, "gitcommitOverflow", { ctermfg = 217, fg = "#ffaabb" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, ctermfg = 158, fg = "#aaf0d1" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "lCursor", { bg = "#ff7799", ctermbg = 210, ctermfg = 233, fg = "#100020" })
hi(0, "markdownH1", { ctermfg = 228, fg = "#ffff99" })
hi(0, "markdownH2", { ctermfg = 147, fg = "#aaaaff" })
hi(0, "markdownH3", { ctermfg = 158, fg = "#aaf0d1" })
hi(0, "markdownH4", { ctermfg = 170, fg = "#ca6ecf" })
hi(0, "markdownH5", { ctermfg = 87, fg = "#42f7ff" })
hi(0, "markdownH6", { ctermfg = 38, fg = "#00a5c5" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#100020"
g.terminal_color_1 = "#ffaabb"
g.terminal_color_2 = "#aaf0d1"
g.terminal_color_3 = "#aaaaff"
g.terminal_color_4 = "#42f7ff"
g.terminal_color_5 = "#ffaaff"
g.terminal_color_6 = "#ca6ecf"
g.terminal_color_7 = "#ff7799"
g.terminal_color_8 = "#8691a7"
g.terminal_color_9 = "#ffaabb"
g.terminal_color_10 = "#aaf0d1"
g.terminal_color_11 = "#aaaaff"
g.terminal_color_12 = "#42f7ff"
g.terminal_color_13 = "#ffaaff"
g.terminal_color_14 = "#ca6ecf"
g.terminal_color_15 = "#9977ff"
